### PR TITLE
Add MySQLi support

### PR DESCRIPTION
**Pull request by alex2534alex**
I think you have to include MySQLi support

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
"I think" is not enough. You must add an example.

For Genisys, SQLite is too enough.

**Comment by FaigerSYS** [comment]
For example some plugins that have a lot of data to save (auth, economy, etc.) using MySQL. Server/SimpleAuth for example

**Comment by FaigerSYS** [comment]
It can be very usefull.

**Comment by ishitatsuyuki** [comment]
Again, SQLite is too enough. MySQL is basically for massive datas.

**Comment by alex2534alex** [comment]
Ohhh. It is useless to persuade....

**Comment by ishitatsuyuki** [comment]
We only add something that is really useful. I'm just making you away from anti-patterns.

**Comment by FaigerSYS** [comment]
Just BIG plugins like SimpleAuth using MySQL. If you do not approve it - so be it

**Comment by ishitatsuyuki** [comment]
BIG? Come again if you ever had as many users as Salesforce or Google; SQLite can handle a lot, MySQL is only for complicated authentication, clustering and more. Nothing worse to use it for MCPE.

**Comment by dktapps** [comment]
There's also nothing stopping you compiling PHP with MySQL if you really need it.

**Pull request closed without merging**
